config/routes.rb
Rails.application.routes.draw do
  resources :score_cards
  resources :user_contests
  resources :user_teams
  resources :contests
  resources :contest_categories
  resources :match_teams
  resources :players
  resources :teams
  #resources :users
  resources :matches
  resources :competitions
  root 'welcome#login'
  mount API::CashApp::Base => '/'

  get '/logout' => 'welcome#logout'
  get '/dashboard' => 'welcome#index'
  get '/invite/:referral_code' => 'welcome#invite'
  match '/login' => 'welcome#login', :via => [:get, :post]
end

app/models/common_contest.rb
class CommonContest < ActiveRecord::Base
  has_many :prize

end

app/models/competition.rb
class Competition < ApplicationRecord
  has_many :matchs  
  validates :cid, uniqueness: true
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
end

app/models/contest.rb
class Contest < ApplicationRecord
  belongs_to :contest_category
  has_many :user_teams
  scope :active, -> {where(status: true).order('created_at desc')}
end

app/models/contest_category.rb
class ContestCategory < ApplicationRecord
  has_many :contests
  validates :title, uniqueness: true
  scope :active, -> {where(status: true).order('created_at desc')}
end

app/models/filter.rb
class Filter < ActiveRecord::Base
end

app/models/kycdetail.rb
class Kycdetail < ActiveRecord::Base
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :competition
  has_many :match_teams
  has_many :user_teams
  scope :active, -> {where(status: true).order('created_at desc')}

  validates :mid, uniqueness: true
end

app/models/match_team.rb
class MatchTeam < ApplicationRecord
  #enum :role, {wk: 0, bat: 1, all: 2, bowl: 3}
  belongs_to :match
  belongs_to :team
  belongs_to :player

  validates_uniqueness_of :mid, scope: :pid
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
  has_many :match_team
  validates :pid, uniqueness: true
end

app/models/prize.rb
class Prize < ActiveRecord::Base
  belongs_to :common_contest
end

app/models/score_card.rb
class ScoreCard < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :players
  has_many :match_teams
  validates :tid, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_teams
  has_many :user_contests
end

app/models/user_contest.rb
class UserContest < ApplicationRecord
  belongs_to :user
end

app/models/user_team.rb
class UserTeam < ApplicationRecord
  belongs_to :user
  belongs_to :match
  belongs_to :contest
end

app/controllers/match_teams_controller.rb
class MatchTeamsController < ApplicationController
  before_action :authorize
  before_action :set_match_team, only: [:show, :edit, :update, :destroy]

  # GET /match_teams
  # GET /match_teams.json
  def index
    @match_teams = MatchTeam.all
  end

  # GET /match_teams/1
  # GET /match_teams/1.json
  def show
  end

  # GET /match_teams/new
  def new
    @match_team = MatchTeam.new
  end

  # GET /match_teams/1/edit
  def edit
  end

  # POST /match_teams
  # POST /match_teams.json
  def create
    @match_team = MatchTeam.new(match_team_params)

    respond_to do |format|
      if @match_team.save
        format.html { redirect_to @match_team, notice: 'Match team was successfully created.' }
        format.json { render :show, status: :created, location: @match_team }
      else
        format.html { render :new }
        format.json { render json: @match_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /match_teams/1
  # PATCH/PUT /match_teams/1.json
  def update
    respond_to do |format|
      if @match_team.update(match_team_params)
        format.html { redirect_to @match_team, notice: 'Match team was successfully updated.' }
        format.json { render :show, status: :ok, location: @match_team }
      else
        format.html { render :edit }
        format.json { render json: @match_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /match_teams/1
  # DELETE /match_teams/1.json
  def destroy
    @match_team.destroy
    respond_to do |format|
      format.html { redirect_to match_teams_url, notice: 'Match team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match_team
      @match_team = MatchTeam.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def match_team_params
      params.fetch(:match_team, {})
    end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/helpers/match_teams_helper.rb
module MatchTeamsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/match_teams/_form.html.erb
<%= form_with(model: match_team, local: true) do |form| %>
  <% if match_team.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match_team.errors.count, "error") %> prohibited this match_team from being saved:</h2>

      <ul>
      <% match_team.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/match_teams/edit.html.erb
<h1>Editing Match Team</h1>

<%= render 'form', match_team: @match_team %>

<%= link_to 'Show', @match_team %> |
<%= link_to 'Back', match_teams_path %>

app/views/match_teams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Match Teams</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @match_teams.each do |match_team| %>
      <tr>
        <td><%= link_to 'Show', match_team %></td>
        <td><%= link_to 'Edit', edit_match_team_path(match_team) %></td>
        <td><%= link_to 'Destroy', match_team, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match Team', new_match_team_path %>

app/views/match_teams/new.html.erb
<h1>New Match Team</h1>

<%= render 'form', match_team: @match_team %>

<%= link_to 'Back', match_teams_path %>

app/views/match_teams/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_match_team_path(@match_team) %> |
<%= link_to 'Back', match_teams_path %>