config/routes.rb
Rails.application.routes.draw do
  resources :score_cards
  resources :user_contests
  resources :user_teams
  resources :contests
  resources :contest_categories
  resources :match_teams
  resources :players
  resources :teams
  #resources :users
  resources :matches
  resources :competitions
  root 'welcome#login'
  mount API::CashApp::Base => '/'

  get '/logout' => 'welcome#logout'
  get '/dashboard' => 'welcome#index'
  get '/invite/:referral_code' => 'welcome#invite'
  match '/login' => 'welcome#login', :via => [:get, :post]
end

app/models/common_contest.rb
class CommonContest < ActiveRecord::Base
  has_many :prize

end

app/models/competition.rb
class Competition < ApplicationRecord
  has_many :matchs  
  validates :cid, uniqueness: true
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
end

app/models/contest.rb
class Contest < ApplicationRecord
  belongs_to :contest_category
  has_many :user_teams
  scope :active, -> {where(status: true).order('created_at desc')}
end

app/models/contest_category.rb
class ContestCategory < ApplicationRecord
  has_many :contests
  validates :title, uniqueness: true
  scope :active, -> {where(status: true).order('created_at desc')}
end

app/models/filter.rb
class Filter < ActiveRecord::Base
end

app/models/kycdetail.rb
class Kycdetail < ActiveRecord::Base
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :competition
  has_many :match_teams
  has_many :user_teams
  scope :active, -> {where(status: true).order('created_at desc')}

  validates :mid, uniqueness: true
end

app/models/match_team.rb
class MatchTeam < ApplicationRecord
  #enum :role, {wk: 0, bat: 1, all: 2, bowl: 3}
  belongs_to :match
  belongs_to :team
  belongs_to :player

  validates_uniqueness_of :mid, scope: :pid
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
  has_many :match_team
  validates :pid, uniqueness: true
end

app/models/prize.rb
class Prize < ActiveRecord::Base
  belongs_to :common_contest
end

app/models/score_card.rb
class ScoreCard < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :players
  has_many :match_teams
  validates :tid, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_teams
  has_many :user_contests
end

app/models/user_contest.rb
class UserContest < ApplicationRecord
  belongs_to :user
end

app/models/user_team.rb
class UserTeam < ApplicationRecord
  belongs_to :user
  belongs_to :match
  belongs_to :contest
end

app/controllers/score_cards_controller.rb
class ScoreCardsController < ApplicationController
  before_action :authorize
  before_action :set_score_card, only: [:show, :edit, :update, :destroy]

  # GET /score_cards
  # GET /score_cards.json
  def index
    @score_cards = ScoreCard.all
  end

  # GET /score_cards/1
  # GET /score_cards/1.json
  def show
  end

  # GET /score_cards/new
  def new
    @score_card = ScoreCard.new
  end

  # GET /score_cards/1/edit
  def edit
  end

  # POST /score_cards
  # POST /score_cards.json
  def create
    @score_card = ScoreCard.new(score_card_params)

    respond_to do |format|
      if @score_card.save
        format.html { redirect_to @score_card, notice: 'Score card was successfully created.' }
        format.json { render :show, status: :created, location: @score_card }
      else
        format.html { render :new }
        format.json { render json: @score_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /score_cards/1
  # PATCH/PUT /score_cards/1.json
  def update
    respond_to do |format|
      if @score_card.update(score_card_params)
        format.html { redirect_to @score_card, notice: 'Score card was successfully updated.' }
        format.json { render :show, status: :ok, location: @score_card }
      else
        format.html { render :edit }
        format.json { render json: @score_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /score_cards/1
  # DELETE /score_cards/1.json
  def destroy
    @score_card.destroy
    respond_to do |format|
      format.html { redirect_to score_cards_url, notice: 'Score card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score_card
      @score_card = ScoreCard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def score_card_params
      params.fetch(:score_card, {})
    end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/score_cards_helper.rb
module ScoreCardsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/score_cards/_form.html.erb
<%= form_with(model: score_card, local: true) do |form| %>
  <% if score_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(score_card.errors.count, "error") %> prohibited this score_card from being saved:</h2>

      <ul>
      <% score_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/score_cards/edit.html.erb
<h1>Editing Score Card</h1>

<%= render 'form', score_card: @score_card %>

<%= link_to 'Show', @score_card %> |
<%= link_to 'Back', score_cards_path %>

app/views/score_cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Score Cards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @score_cards.each do |score_card| %>
      <tr>
        <td><%= link_to 'Show', score_card %></td>
        <td><%= link_to 'Edit', edit_score_card_path(score_card) %></td>
        <td><%= link_to 'Destroy', score_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score Card', new_score_card_path %>

app/views/score_cards/new.html.erb
<h1>New Score Card</h1>

<%= render 'form', score_card: @score_card %>

<%= link_to 'Back', score_cards_path %>

app/views/score_cards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_score_card_path(@score_card) %> |
<%= link_to 'Back', score_cards_path %>