config/routes.rb
Rails.application.routes.draw do
  resources :score_cards
  resources :user_contests
  resources :user_teams
  resources :contests
  resources :contest_categories
  resources :match_teams
  resources :players
  resources :teams
  #resources :users
  resources :matches
  resources :competitions
  root 'welcome#login'
  mount API::CashApp::Base => '/'

  get '/logout' => 'welcome#logout'
  get '/dashboard' => 'welcome#index'
  get '/invite/:referral_code' => 'welcome#invite'
  match '/login' => 'welcome#login', :via => [:get, :post]
end

app/models/common_contest.rb
class CommonContest < ActiveRecord::Base
  has_many :prize

end

app/models/competition.rb
class Competition < ApplicationRecord
  has_many :matchs  
  validates :cid, uniqueness: true
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
end

app/models/contest.rb
class Contest < ApplicationRecord
  belongs_to :contest_category
  has_many :user_teams
  scope :active, -> {where(status: true).order('created_at desc')}
end

app/models/contest_category.rb
class ContestCategory < ApplicationRecord
  has_many :contests
  validates :title, uniqueness: true
  scope :active, -> {where(status: true).order('created_at desc')}
end

app/models/filter.rb
class Filter < ActiveRecord::Base
end

app/models/kycdetail.rb
class Kycdetail < ActiveRecord::Base
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :competition
  has_many :match_teams
  has_many :user_teams
  scope :active, -> {where(status: true).order('created_at desc')}

  validates :mid, uniqueness: true
end

app/models/match_team.rb
class MatchTeam < ApplicationRecord
  #enum :role, {wk: 0, bat: 1, all: 2, bowl: 3}
  belongs_to :match
  belongs_to :team
  belongs_to :player

  validates_uniqueness_of :mid, scope: :pid
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
  has_many :match_team
  validates :pid, uniqueness: true
end

app/models/prize.rb
class Prize < ActiveRecord::Base
  belongs_to :common_contest
end

app/models/score_card.rb
class ScoreCard < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :players
  has_many :match_teams
  validates :tid, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_teams
  has_many :user_contests
end

app/models/user_contest.rb
class UserContest < ApplicationRecord
  belongs_to :user
end

app/models/user_team.rb
class UserTeam < ApplicationRecord
  belongs_to :user
  belongs_to :match
  belongs_to :contest
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :authorize
  before_action :set_competition, only: [:show, :edit, :update, :destroy]

  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.all.order('created_at desc').paginate(:page => params[:page], :per_page => PER_PAGE)
    #@competitions = Competition.where("created_at >= ?", Date.today).order('created_at desc').paginate(:page => params[:page], :per_page => PER_PAGE)
  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
  end

  # GET /competitions/new
  def new
    @competition = Competition.new
  end

  # GET /competitions/1/edit
  def edit
  end

  # POST /competitions
  # POST /competitions.json
  def create
    @competition = Competition.new(competition_params)

    respond_to do |format|
      if @competition.save
        format.html { redirect_to @competition, notice: 'Competition was successfully created.' }
        format.json { render :show, status: :created, location: @competition }
      else
        format.html { render :new }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitions/1
  # PATCH/PUT /competitions/1.json
  def update
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to @competition, notice: 'Competition was successfully updated.' }
        format.json { render :show, status: :ok, location: @competition }
      else
        format.html { render :edit }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    @competition.destroy
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: 'Competition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition
      @competition = Competition.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def competition_params
      #params.fetch(:competition, {})
      params.require(:competition).permit(:title, :cid, :abbr, :category, :total_teams,
        :game_format, :status, :status_str, :season, :date_start, :country, :status,
        :date_end, :total_matches, :total_rounds)
    end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/competitions/_form.html.erb
<%= form_with(model: competition, local: true) do |form| %>
  <% if competition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

      <ul>
      <% competition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!-- /.row -->
  <div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Basic Form Elements
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-6">
            <div class="form-group">
              <label>Title</label>
              <%= form.text_field :title, class: "form-control", placeholder: "Enter title", :required => true %>       
            </div>
            <div class="form-group">
              <label>Abbr</label>
              <%= form.text_field :abbr, class: "form-control", placeholder: "Enter abbr", :required => true %>
            </div>
            <div class="form-group">
              <label>Category</label>
              <%= form.text_field :category, class: "form-control", placeholder: "Enter category", :required => true %>
            </div>
            <div class="form-group">
              <label>GameFormat</label>
              <%= form.text_field :game_format, class: "form-control", placeholder: "Enter game format", :required => true %>
            </div>
            <div class="form-group">
              <label>StatusStr</label>
              <%= form.text_field :status_str, class: "form-control", placeholder: "Enter status str", :required => true %>
            </div>
            <div class="form-group">
              <label>Status</label>
              <%= form.select :status, options_for_select([['Active', true], ['Pause', false]], selected: form.object.status),{}, {class: 'form-control'} %>
            </div>

            <button type="submit" class="btn btn-primary">Submit Record</button>
            <button type="reset" class="btn btn-default">Reset Form</button>
          </div>

          <!-- /.col-lg-6 (nested) -->
          <div class="col-lg-6">
            <div class="form-group">
              <label>Country</label>
              <%= form.text_field :country, class: "form-control", placeholder: "Enter country", :required => true %>
            </div>
            <div class="form-group">
              <label>Season</label>
              <%= form.text_field :season, class: "form-control", placeholder: "Enter season", :required => true %>
            </div>
            <div class="form-group">
              <label>DateStart</label>
              <%= form.text_field :date_start, class: "form-control", placeholder: "Enter date start", :required => true %>
            </div>
            <div class="form-group">
              <label>DateEnd</label>
              <%= form.text_field :date_end, class: "form-control", placeholder: "Enter date end", :required => true %>
            </div>
            <div class="form-group">
              <label>TotalMatches</label>
              <%= form.text_field :total_matches, class: "form-control", placeholder: "Enter total matches", :required => true %>
            </div>
            <div class="form-group">
              <label>TotalRounds</label>
              <%= form.text_field :total_rounds, class: "form-control", placeholder: "Enter total rounds", :required => true %>
            </div>
            <div class="form-group">
              <label>TotalTeams</label>
              <%= form.text_field :total_teams, class: "form-control", placeholder: "Enter total teams", :required => true %>
            </div>                  
          </div>
          <!-- /.col-lg-6 (nested) -->
        </div>
        <!-- /.row (nested) -->
      </div>
      <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
  </div>
  <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<% end %>

app/views/competitions/edit.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h2 class="page-header">Editing Competition</h2>
      <b><%= link_to 'Back', @competition %></b>
    </div>
  </div>
  <%= render 'form', competition: @competition %>
  <b><%= link_to 'Back', @competition %></b>
</div>
<%#= link_to 'Show', @competition %>

app/views/competitions/index.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <p id="notice" style="color:orange;"><%= notice %></p>
      <div class="col-lg-12">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">Listing Competitions</h2>
      </div>
      <div class="form-group">
        <%= form_tag('/search-competitions', :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], class: 'form-control', :required => true, placeholder: 'Which Competitions you are looking for?' %>          
        <% end %>        
      </div>
      <table class="table table-responsive table-bordered">
        <thead>
          <tr>
            <th>Id/Cid</th>            
            <th>Title</th>
            <th>Abbr</th>            
            <th>Category</th>
            <th>Format</th>
            <th>Status</th>
            <th>Status</th>           
            <th>DateStart</th>
            <th colspan="3">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @competitions.each do |competition| %>
          <tr>
            <td><%= competition.id %>/<%= competition.try(:cid) %></td>
            <td><%= competition.try(:title) %></td>
            <td><%= competition.try(:abbr) %></td>
            <td><%= competition.try(:category) %></td>
            <td><%= competition.try(:game_format) %></td>
            <td><%= competition.try(:status_str) %></td>            
            <td>
              <% if competition.try(:status) == true %>
                <p style="color:green;">Active</p>              
              <% else %>
                <p style="color:red;">Paused</p>
              <% end %>
            </td>
            <td><%= competition.try(:created_at).strftime("%d/%m/%Y %I:%M%p")  %></td>            
            <td><%= link_to 'Show', competition %></td>
            <%#= link_to 'Edit', edit_competition_path(competition) %>
            <%#= link_to 'Destroy', competition, method: :delete, data: { confirm: 'Are you sure?' } %>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @competitions %>
      <br>
      <%= link_to 'New Competition', new_competition_path %>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->

app/views/competitions/new.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h2 class="page-header">New Competition</h2>
    </div>
  </div>
  <%= render 'form', competition: @competition %>
  <b><%= link_to 'Back', competitions_path %></b>
</div>

app/views/competitions/show.html.erb
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <p id="notice" style="color:orange;"><%= notice %></p>
      <div class="col-lg-12">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">Showing Competition Details</h2>        
        <b><%= link_to 'Edit', edit_competition_path(@competition) %> |
          <%= link_to 'Back', competitions_path %></b>        
      </div>
      <table class="table table-responsive table-bordered">
        <thead>
          <tr>
            <th>Id</th>
            <th>Cid</th>
            <th>Title</th>
            <th>Abbr</th>
            <th>Category</th>
            <th>GameFormat</th>
            <th>Status</th>
            <th>StatusStr</th>            
          </tr>
        </thead>
        <tbody>          
          <tr>
            <td><%= @competition.id %></td>
            <td><%= @competition.try(:cid) %></td>
            <td><%= @competition.try(:title) %></td>
            <td><%= @competition.try(:abbr) %></td>
            <td><%= @competition.try(:category) %></td>
            <td><%= @competition.try(:game_format) %></td>
            <td><%= @competition.try(:status) %></td>
            <td><%= @competition.try(:status_str) %></td>
          </tr>          
        </tbody>
      </table>
      <table class="table table-responsive table-bordered">
        <thead>
          <tr>
            <th>Season</th>
            <th>DateStart</th>
            <th>DateEnd</th>
            <th>TotalMatches</th>
            <th>TotalRounds</th>
            <th>TotalTeams</th>
            <th>Country</th>
            <th>CreatedTime</th>            
          </tr>
        </thead>
        <tbody>          
          <tr>
            <td><%= @competition.try(:season) %></td>
            <td><%= @competition.try(:date_start) %></td>
            <td><%= @competition.try(:date_end) %></td>
            <td><%= @competition.try(:total_matches) %></td>
            <td><%= @competition.try(:total_rounds) %></td>
            <td><%= @competition.try(:total_teams) %></td>
            <td><%= @competition.try(:country) %></td>
            <td><%= @competition.try(:created_at).strftime("%d/%m/%Y %I:%M%p")  %></td> 
          </tr>          
        </tbody>
      </table>
    </div>
  </div>
</div>