config/routes.rb
Rails.application.routes.draw do
  resources :score_cards
  resources :user_contests
  resources :user_teams
  resources :contests
  resources :contest_categories
  resources :match_teams
  resources :players
  resources :teams
  #resources :users
  resources :matches
  resources :competitions
  root 'welcome#login'
  mount API::CashApp::Base => '/'

  get '/logout' => 'welcome#logout'
  get '/dashboard' => 'welcome#index'
  get '/invite/:referral_code' => 'welcome#invite'
  match '/login' => 'welcome#login', :via => [:get, :post]
end

app/models/common_contest.rb
class CommonContest < ActiveRecord::Base
  has_many :prize

end

app/models/competition.rb
class Competition < ApplicationRecord
  has_many :matchs  
  validates :cid, uniqueness: true
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
end

app/models/contest.rb
class Contest < ApplicationRecord
  belongs_to :contest_category
  has_many :user_teams
  scope :active, -> {where(status: true).order('created_at desc')}
end

app/models/contest_category.rb
class ContestCategory < ApplicationRecord
  has_many :contests
  validates :title, uniqueness: true
  scope :active, -> {where(status: true).order('created_at desc')}
end

app/models/filter.rb
class Filter < ActiveRecord::Base
end

app/models/kycdetail.rb
class Kycdetail < ActiveRecord::Base
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :competition
  has_many :match_teams
  has_many :user_teams
  scope :active, -> {where(status: true).order('created_at desc')}

  validates :mid, uniqueness: true
end

app/models/match_team.rb
class MatchTeam < ApplicationRecord
  #enum :role, {wk: 0, bat: 1, all: 2, bowl: 3}
  belongs_to :match
  belongs_to :team
  belongs_to :player

  validates_uniqueness_of :mid, scope: :pid
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
  has_many :match_team
  validates :pid, uniqueness: true
end

app/models/prize.rb
class Prize < ActiveRecord::Base
  belongs_to :common_contest
end

app/models/score_card.rb
class ScoreCard < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :players
  has_many :match_teams
  validates :tid, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_teams
  has_many :user_contests
end

app/models/user_contest.rb
class UserContest < ApplicationRecord
  belongs_to :user
end

app/models/user_team.rb
class UserTeam < ApplicationRecord
  belongs_to :user
  belongs_to :match
  belongs_to :contest
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authorize
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all.order('created_at desc').paginate(:page => params[:page], :per_page => PER_PAGE)
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def match_params
      params.require(:match).permit(:status)
    end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/user_teams_helper.rb
module UserTeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/matches/_form.html.erb
<div class="container">
    <%= form_with(model: match, local: true) do |form| %>
    <% if match.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

        <ul>
          <% match.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            Basic Form Elements
          </div>
          <div class="panel-body">
            <div class="row">
              <div class="col-lg-6">
                <div class="form-group">
                  <label>Title</label>
                  <%= form.text_field :title, class: "form-control", placeholder: "Enter title", :required => true,:disabled => true %>
                </div>
                <div class="form-group">
                  <label>Subtitle</label>
                  <%= form.text_field :subtitle, class: "form-control", placeholder: "Enter description", :required => true,:disabled => true %>
                </div>

                <div class="form-group">
                  <label>Status</label>
                  <%= form.select :status, options_for_select([['Active', true], ['Pause', false]], selected: form.object.status),{}, {class: 'form-control'} %>
                </div>
                <button type="submit" class="btn btn-primary">Submit Record</button>
                <button type="reset" class="btn btn-default">Reset Form</button>
              </div>
            </div>
            <!-- /.row (nested) -->
          </div>
          <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
      </div>
      <!-- /.col-lg-12 -->
    </div>
  <% end %>
</div>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <p id="notice" style="color:orange;"><%= notice %></p>
      <div class="col-lg-12">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">Listing Matches</h2>
      </div>
      <div class="form-group">
        <%= form_tag('/search-matches', :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], class: 'form-control', :required => true, placeholder: 'Which Match you are looking for?' %>          
        <% end %>        
      </div>
      <table class="table table-responsive table-bordered">
        <thead>
          <tr>
            <th>Id|Mid</th>            
            <th>Title</th>
            <th>STitle</th>            
            <th>Subtitle</th>            
            <th>FormatStr</th>
            <th>StatusStr</th>           
            <th>DateTime</th>
            <th colspan="3">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @matches.each do |match| %>
          <tr>
            <td><%= match.id %>|<%= match.try(:mid) %></td>            
            <td><%= match.try(:title) %></td>
            <td><%= match.try(:short_title) %></td>
            <td><%= match.try(:subtitle) %></td>
            <td><%= match.try(:mformat_str) %></td>
            <td><%= match.try(:status_str) %></td>            
            <td>
              <% if match.try(:status) == true %>
                <p style="color:green;">Active</p>              
              <% else %>
                <p style="color:red;">Paused</p>
              <% end %>
            </td>
            <td><%= match.try(:created_at).strftime("%d/%m/%Y %I:%M%p")  %></td>            
            <td><%= link_to 'Show', match %>
            <%#= link_to 'Edit', edit_match_path(match) %>
            <%#= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @matches %>
      <br>
      <%#= link_to 'New Match', new_match_path %>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <p id="notice" style="color:orange;"><%= notice %></p>
      <div class="col-lg-12">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">Showing Match Details</h2>        
        <b><%= link_to 'Edit', edit_match_path(@match) %> |
         <%= link_to 'Back', matches_path %></b>        
      </div>
      <table class="table table-responsive table-bordered">
        <thead>
          <tr>
            <th>Id|Mid|Cid</th>
            <th>Title</th>
            <th>ShortTitle</th>
            <th>Subtitle</th>
            <th>Mnumber</th>
            <th>mformat</th>
            <th>mformatStr</th>
            <th>mStatus</th>
            <th>StatusStr</th>          
          </tr>
        </thead>
        <tbody>          
          <tr>
            <td><%= @match.id %>|<%= @match.mid %>|<%= @match.cid %></td>
            <td><%= @match.try(:title) %></td>
            <td><%= @match.try(:short_title) %></td>
            <td><%= @match.try(:subtitle) %></td>
            <td><%= @match.try(:mnumber) %></td>
            <td><%= @match.try(:mformat) %></td>
            <td><%= @match.try(:mformat_str) %></td>            
            <td><%= @match.try(:mstatus) %></td>
            <td><%= @match.try(:mstatus_str) %></td>           
          </tr>          
        </tbody>
      </table>
      <table class="table table-responsive table-bordered">
        <thead>
          <tr>
            <th>mstatus_note</th>
            <th>domestic</th>
            <th>odds_available</th>
            <th>Winning%</th>
            <th>Commission</th>
            <th>Discount</th>
            <th>Bonus</th>
            <th>Status</th>            
          </tr>
        </thead>
        <tbody>          
          <tr>
            <td><%= @match.try(:mstatus_note) %></td>
            <td><%= @match.try(:domestic) %></td>
            <td><%= @match.try(:odds_available) %></td>
            <td><%= @match.try(:winning_percentage) %></td>            
            <td><%= @match.try(:game_state) %></td>
            <td><%= @match.try(:game_state_str) %></td>
            <td><%= @match.try(:date_start) %></td>
            <td><%= @match.try(:date_end) %></td> 
          </tr>          
        </tbody>
      </table>
    </div>
  </div>
</div>